name: CI
on:
  pull_request: ~

env:
  DEVBOX_VERSION: '0.13.1'

permissions:
  contents: read
  # to comment on PRs
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  validate_cog_config:
    name: Validate cog config
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Setup cog
        uses: ./.github/actions/setup-cog

      - name: Validate cog's config
        run: |
          cog inspect --config .cog/config.yaml \
            --ir builders
