name: CI
on:
  pull_request: ~

env:
  DEVBOX_VERSION: '0.13.1'
  PROMQL_BUILDER_REPO: 'https://github.com/grafana/promql-builder.git'

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  validate_cog_config:
    name: Validate cog config
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - name: Setup cog
        uses: ./.github/actions/setup-cog

      - name: Validate cog's config
        run: |
          cog inspect --config .cog/config.yaml \
            --ir builders
        env:
          PATH: ${{ steps.setup-cog.outputs.bin-path }}:${{ env.PATH }}

  diff_preview:
    name: Generate diff
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - name: Setup cog
        uses: ./.github/actions/setup-cog

      - name: Install devbox
        uses: jetify-com/devbox-install-action@a03caf5813591bc882139eba6ae947930a83a427 #v0.11.0
        with:
          enable-cache: 'true'
          devbox-version: ${{ env.DEVBOX_VERSION }}

      - name: Dry-run release with current branch
        run: |
          git config --global user.email "cog-ci@grafana.com"
          git config --global user.name "cog - CI"

          devbox run ./scripts/release.sh

          mv /tmp/promql-builder-current/promql-builder ./promql-builder-current
        env:
          TERM: 'xterm'
          WORKSPACE_PATH: /tmp/promql-builder-current
          CLEANUP_WORKSPACE: 'no'
          LOG_LEVEL: '7' # debug
          GOGC: 'off'
          PATH: ${{ steps.setup-cog.outputs.bin-path }}:${{ env.PATH }}

      - name: Checkout main branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          ref: main
          path: promql-builder-main
          persist-credentials: false

      - name: Preview diff
        run: |
          cat <<'EOF' > preview.md
          <!-- promql-builder-diff-preview-marker -->
          
          **Note:** the diff show code changes that would be introduced by this PR.
          
          <details>
          <summary>
          
          ### 🔎 Changes to `promql-builder@main`
          
          </summary>
          
          ```patch
          EOF
          
          diff \
            --new-file \
            --unidirectional-new-file \
            --color=never \
            --unified \
            --recursive \
            --exclude='.git' \
            --exclude='gradle.properties' \
            --exclude='pyproject.toml' \
            --exclude='package.json' \
            --exclude='*.md' \
            ./promql-builder-main ./promql-builder-current >> preview.md || true # diff returns 1 if the two targets have differences
          
          cat <<'EOF' >> preview.md
          ```
          </details>
          EOF

      - name: Find preview comment
        uses: peter-evans/find-comment@a0b5124c1959e5e7c25efa20d957d507d54a6f4e  #v3.1.0
        id: preview-comment-find
        # only run on main repo, and not on dependabot PRs
        if: "!contains(github.actor, 'dependabot') && github.repository == 'grafana/promql-builder'"
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'promql-builder-diff-preview-marker'

      - name: Upsert preview comment
        uses: peter-evans/create-or-update-comment@17c956346987a35d40d2d723c6930f90f594400d #v4.0.0
        # only run on main repo, and not on dependabot PRs
        if: "!contains(github.actor, 'dependabot') && github.repository == 'grafana/promql-builder'"
        with:
          comment-id: ${{ steps.preview-comment-find.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body-path: './preview.md'
