name: Python Release
on:
  push:
    tags: ['v*']

env:
  DEVBOX_VERSION: '0.13.1'

# See https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
jobs:
  release:
    name: Release Python package
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # mandatory for trusted publishing

    environment:
      name: pypi
      url: https://pypi.org/p/promql_builder

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Install devbox
        uses: jetify-com/devbox-install-action@a03caf5813591bc882139eba6ae947930a83a427 #v0.11.0
        with:
          enable-cache: 'true'
          devbox-version: ${{ env.DEVBOX_VERSION }}

      - name: Build a binary wheel and a source tarball
        run: devbox run ./scripts/build-python-wheel.sh

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist/
          attestations: false
